/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Task {
  'id' : TaskId,
  'title' : string,
  'procrastinated' : boolean,
  'createdAt' : Time,
  'completed' : boolean,
  'description' : string,
  'updatedAt' : Time,
  'reminderTime' : [] | [bigint],
}
export type TaskId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[TaskId], undefined>,
  'createTask' : ActorMethod<[string, string, [] | [bigint]], Task>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAutoReset' : ActorMethod<[], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNotificationsEnabled' : ActorMethod<[], boolean>,
  'getTasksForDay' : ActorMethod<[bigint], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAutoReset' : ActorMethod<[boolean], undefined>,
  'setNotificationsEnabled' : ActorMethod<[boolean], undefined>,
  'toggleProcrastination' : ActorMethod<[TaskId], undefined>,
  'updateTask' : ActorMethod<[TaskId, string, string, [] | [bigint]], Task>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];