/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskId = IDL.Nat;
export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'procrastinated' : IDL.Bool,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'reminderTime' : IDL.Opt(IDL.Int),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([TaskId], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Int)], [Task], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAutoReset' : IDL.Func([], [IDL.Bool], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotificationsEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'getTasksForDay' : IDL.Func([IDL.Int], [IDL.Vec(Task)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAutoReset' : IDL.Func([IDL.Bool], [], []),
  'setNotificationsEnabled' : IDL.Func([IDL.Bool], [], []),
  'toggleProcrastination' : IDL.Func([TaskId], [], []),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
      [Task],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskId = IDL.Nat;
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'procrastinated' : IDL.Bool,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'reminderTime' : IDL.Opt(IDL.Int),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([TaskId], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Int)], [Task], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAutoReset' : IDL.Func([], [IDL.Bool], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotificationsEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getTasksForDay' : IDL.Func([IDL.Int], [IDL.Vec(Task)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAutoReset' : IDL.Func([IDL.Bool], [], []),
    'setNotificationsEnabled' : IDL.Func([IDL.Bool], [], []),
    'toggleProcrastination' : IDL.Func([TaskId], [], []),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, IDL.Opt(IDL.Int)],
        [Task],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };